<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Technological</name>
   <tag></tag>
   <elementGuidId>469dd58a-e9b5-48b0-83f4-c2b7b7f1cb27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarNavDropdown']/ul/li[4]/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.sub-menu > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>beab0b73-95c3-4fb1-a25c-762ce7baa02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/technological</value>
      <webElementGuid>a34163d8-5ade-42cb-aa60-6c74c409f356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Technological</value>
      <webElementGuid>7b93e39f-f5fc-4586-8f60-721aa17f4333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarNavDropdown&quot;)/ul[@class=&quot;nav navbar-nav&quot;]/li[4]/ul[@class=&quot;sub-menu&quot;]/li[4]/a[1]</value>
      <webElementGuid>d2be35a6-2a0f-4091-91ae-411ed69ac79d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarNavDropdown']/ul/li[4]/ul/li[4]/a</value>
      <webElementGuid>9248193c-cb5f-451e-be8b-db373db41bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Technological')]</value>
      <webElementGuid>b64b0c33-a80b-441d-849c-cb24a6dcd534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Social'])[1]/following::a[1]</value>
      <webElementGuid>55f3830c-23ab-458e-a70e-c9a8086481cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarkable Customers'])[1]/following::a[2]</value>
      <webElementGuid>4e4b502e-0d37-4fc3-a3c4-b8161d9b586a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compliance'])[1]/preceding::a[1]</value>
      <webElementGuid>2d63cc95-7a93-48a6-8689-18dd3db81729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News &amp; Media'])[1]/preceding::a[2]</value>
      <webElementGuid>81aeeb6e-ec49-4758-9611-07985df51daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Technological']/parent::*</value>
      <webElementGuid>13e3191c-390a-4885-a51f-92889a938e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/technological')]</value>
      <webElementGuid>c3056950-c595-456a-a847-888f4ee0825c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[4]/a</value>
      <webElementGuid>55f79a4a-f6b5-4406-ae3c-e70f6d9802fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/technological' and (text() = 'Technological' or . = 'Technological')]</value>
      <webElementGuid>db5f5c19-9f09-4b3c-ad21-975fb8e65b79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
